// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "contatore_no_io.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic contatore_no_io::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<1> contatore_no_io::ap_ST_fsm_state1 = "1";
const sc_lv<32> contatore_no_io::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> contatore_no_io::ap_const_lv1_0 = "0";
const sc_lv<1> contatore_no_io::ap_const_lv1_1 = "1";
const sc_lv<32> contatore_no_io::ap_const_lv32_1 = "1";
const sc_lv<32> contatore_no_io::ap_const_lv32_16E35FF = "1011011100011010111111111";
const sc_logic contatore_no_io::ap_const_logic_0 = sc_dt::Log_0;
const bool contatore_no_io::ap_const_boolean_1 = true;

contatore_no_io::contatore_no_io(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_phi_mux_counter_value_new_phi_fu_40_p4);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_fu_68_p2 );
    sensitive << ( counter_value_assign_fu_61_p2 );

    SC_METHOD(thread_ap_phi_mux_led_status_V_loc_phi_fu_50_p4);
    sensitive << ( led_status_V );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_fu_68_p2 );
    sensitive << ( val_assign_fu_79_p2 );

    SC_METHOD(thread_counter_value_assign_fu_61_p2);
    sensitive << ( counter_value );

    SC_METHOD(thread_led_output_V);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_phi_mux_led_status_V_loc_phi_fu_50_p4 );

    SC_METHOD(thread_tmp_fu_68_p2);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( counter_value_assign_fu_61_p2 );

    SC_METHOD(thread_val_assign_fu_79_p2);
    sensitive << ( led_status_V );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    counter_value = "00000000000000000000000000000000";
    led_status_V = "0";
    ap_CS_fsm = "1";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "contatore_no_io_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, led_output_V, "(port)led_output_V");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, counter_value, "counter_value");
    sc_trace(mVcdFile, led_status_V, "led_status_V");
    sc_trace(mVcdFile, ap_phi_mux_counter_value_new_phi_fu_40_p4, "ap_phi_mux_counter_value_new_phi_fu_40_p4");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, tmp_fu_68_p2, "tmp_fu_68_p2");
    sc_trace(mVcdFile, counter_value_assign_fu_61_p2, "counter_value_assign_fu_61_p2");
    sc_trace(mVcdFile, val_assign_fu_79_p2, "val_assign_fu_79_p2");
    sc_trace(mVcdFile, ap_phi_mux_led_status_V_loc_phi_fu_50_p4, "ap_phi_mux_led_status_V_loc_phi_fu_50_p4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("contatore_no_io.hdltvin.dat");
    mHdltvoutHandle.open("contatore_no_io.hdltvout.dat");
}

contatore_no_io::~contatore_no_io() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void contatore_no_io::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        counter_value = ap_phi_mux_counter_value_new_phi_fu_40_p4.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(tmp_fu_68_p2.read(), ap_const_lv1_1))) {
        led_status_V = val_assign_fu_79_p2.read();
    }
}

void contatore_no_io::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void contatore_no_io::thread_ap_phi_mux_counter_value_new_phi_fu_40_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_68_p2.read())) {
            ap_phi_mux_counter_value_new_phi_fu_40_p4 = counter_value_assign_fu_61_p2.read();
        } else if (esl_seteq<1,1,1>(tmp_fu_68_p2.read(), ap_const_lv1_1)) {
            ap_phi_mux_counter_value_new_phi_fu_40_p4 = ap_const_lv32_0;
        } else {
            ap_phi_mux_counter_value_new_phi_fu_40_p4 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        }
    } else {
        ap_phi_mux_counter_value_new_phi_fu_40_p4 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void contatore_no_io::thread_ap_phi_mux_led_status_V_loc_phi_fu_50_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_68_p2.read())) {
            ap_phi_mux_led_status_V_loc_phi_fu_50_p4 = led_status_V.read();
        } else if (esl_seteq<1,1,1>(tmp_fu_68_p2.read(), ap_const_lv1_1)) {
            ap_phi_mux_led_status_V_loc_phi_fu_50_p4 = val_assign_fu_79_p2.read();
        } else {
            ap_phi_mux_led_status_V_loc_phi_fu_50_p4 =  (sc_lv<1>) ("X");
        }
    } else {
        ap_phi_mux_led_status_V_loc_phi_fu_50_p4 =  (sc_lv<1>) ("X");
    }
}

void contatore_no_io::thread_counter_value_assign_fu_61_p2() {
    counter_value_assign_fu_61_p2 = (!counter_value.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(counter_value.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void contatore_no_io::thread_led_output_V() {
    led_output_V = ap_phi_mux_led_status_V_loc_phi_fu_50_p4.read();
}

void contatore_no_io::thread_tmp_fu_68_p2() {
    tmp_fu_68_p2 = (!counter_value_assign_fu_61_p2.read().is_01() || !ap_const_lv32_16E35FF.is_01())? sc_lv<1>(): (sc_biguint<32>(counter_value_assign_fu_61_p2.read()) > sc_biguint<32>(ap_const_lv32_16E35FF));
}

void contatore_no_io::thread_val_assign_fu_79_p2() {
    val_assign_fu_79_p2 = (led_status_V.read() ^ ap_const_lv1_1);
}

void contatore_no_io::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<1>) ("X");
            break;
    }
}

void contatore_no_io::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"led_output_V\" :  \"" << led_output_V.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

