// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Filter2D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read,
        p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write,
        p_dst_data_stream_1_V_din,
        p_dst_data_stream_1_V_full_n,
        p_dst_data_stream_1_V_write,
        p_dst_data_stream_2_V_din,
        p_dst_data_stream_2_V_full_n,
        p_dst_data_stream_2_V_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_pp0_stage0 = 5'd8;
parameter    ap_ST_fsm_state7 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] p_src_data_stream_0_V_dout;
input   p_src_data_stream_0_V_empty_n;
output   p_src_data_stream_0_V_read;
input  [7:0] p_src_data_stream_1_V_dout;
input   p_src_data_stream_1_V_empty_n;
output   p_src_data_stream_1_V_read;
input  [7:0] p_src_data_stream_2_V_dout;
input   p_src_data_stream_2_V_empty_n;
output   p_src_data_stream_2_V_read;
output  [7:0] p_dst_data_stream_0_V_din;
input   p_dst_data_stream_0_V_full_n;
output   p_dst_data_stream_0_V_write;
output  [7:0] p_dst_data_stream_1_V_din;
input   p_dst_data_stream_1_V_full_n;
output   p_dst_data_stream_1_V_write;
output  [7:0] p_dst_data_stream_2_V_din;
input   p_dst_data_stream_2_V_full_n;
output   p_dst_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_0_V_read;
reg p_src_data_stream_1_V_read;
reg p_src_data_stream_2_V_read;
reg p_dst_data_stream_0_V_write;
reg p_dst_data_stream_1_V_write;
reg p_dst_data_stream_2_V_write;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_data_stream_0_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond461_i_reg_2508;
reg   [0:0] or_cond_i_i_reg_2517;
reg   [0:0] icmp_reg_2461;
reg   [0:0] tmp_1_reg_2452;
reg    p_src_data_stream_1_V_blk_n;
reg    p_src_data_stream_2_V_blk_n;
reg    p_dst_data_stream_0_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] or_cond_i_reg_2557;
reg   [0:0] or_cond_i_reg_2557_pp0_iter1_reg;
reg    p_dst_data_stream_1_V_blk_n;
reg    p_dst_data_stream_2_V_blk_n;
reg   [9:0] t_V_2_reg_530;
wire   [1:0] tmp_6_fu_541_p2;
wire    ap_CS_fsm_state2;
wire   [0:0] exitcond462_i_fu_557_p2;
wire    ap_CS_fsm_state3;
wire   [8:0] i_V_fu_563_p2;
reg   [8:0] i_V_reg_2447;
wire   [0:0] tmp_1_fu_569_p2;
wire   [0:0] tmp_71_0_0_not_fu_575_p2;
reg   [0:0] tmp_71_0_0_not_reg_2456;
wire   [0:0] icmp_fu_591_p2;
wire   [0:0] tmp_9_fu_597_p2;
reg   [0:0] tmp_9_reg_2466;
wire   [0:0] tmp_115_0_1_fu_603_p2;
reg   [0:0] tmp_115_0_1_reg_2470;
wire   [0:0] tmp_2_fu_609_p2;
reg   [0:0] tmp_2_reg_2474;
wire   [1:0] row_assign_9_0_0_t_fu_763_p2;
reg   [1:0] row_assign_9_0_0_t_reg_2487;
wire   [1:0] row_assign_9_0_1_t_fu_801_p2;
reg   [1:0] row_assign_9_0_1_t_reg_2494;
wire   [1:0] row_assign_9_0_2_t_fu_839_p2;
reg   [1:0] row_assign_9_0_2_t_reg_2501;
wire   [0:0] exitcond461_i_fu_849_p2;
wire    ap_block_state4_pp0_stage0_iter0;
reg    ap_predicate_op210_read_state5;
reg    ap_predicate_op222_read_state5;
reg    ap_predicate_op274_read_state5;
reg    ap_predicate_op286_read_state5;
reg    ap_predicate_op335_read_state5;
reg    ap_predicate_op344_read_state5;
reg    ap_block_state5_pp0_stage0_iter1;
reg    ap_block_state6_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [9:0] j_V_fu_855_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] or_cond_i_i_fu_903_p2;
wire   [1:0] tmp_50_fu_963_p1;
reg   [1:0] tmp_50_reg_2521;
wire   [0:0] brmerge_fu_967_p2;
reg   [0:0] brmerge_reg_2526;
reg   [9:0] k_buf_0_val_3_addr_reg_2539;
reg   [9:0] k_buf_0_val_4_addr_reg_2545;
reg   [9:0] k_buf_0_val_5_addr_reg_2551;
wire   [0:0] or_cond_i_fu_985_p2;
reg   [9:0] k_buf_1_val_3_addr_reg_2561;
reg   [9:0] k_buf_1_val_4_addr_reg_2567;
reg   [9:0] k_buf_1_val_5_addr_reg_2573;
reg   [9:0] k_buf_2_val_3_addr_reg_2579;
reg   [9:0] k_buf_2_val_4_addr_reg_2585;
reg   [9:0] k_buf_2_val_5_addr_reg_2591;
wire   [7:0] src_kernel_win_0_va_7_fu_1147_p3;
reg   [7:0] src_kernel_win_0_va_7_reg_2597;
wire   [10:0] tmp2_fu_1251_p2;
reg   [10:0] tmp2_reg_2603;
wire   [9:0] tmp4_fu_1257_p2;
reg   [9:0] tmp4_reg_2608;
wire   [7:0] tmp5_fu_1263_p2;
reg   [7:0] tmp5_reg_2613;
wire   [7:0] tmp7_fu_1269_p2;
reg   [7:0] tmp7_reg_2618;
wire   [7:0] src_kernel_win_1_va_7_fu_1418_p3;
reg   [7:0] src_kernel_win_1_va_7_reg_2623;
wire   [10:0] tmp10_fu_1522_p2;
reg   [10:0] tmp10_reg_2629;
wire   [9:0] tmp12_fu_1528_p2;
reg   [9:0] tmp12_reg_2634;
wire   [7:0] tmp13_fu_1534_p2;
reg   [7:0] tmp13_reg_2639;
wire   [7:0] tmp15_fu_1540_p2;
reg   [7:0] tmp15_reg_2644;
wire   [7:0] src_kernel_win_2_va_10_fu_1671_p3;
reg   [7:0] src_kernel_win_2_va_10_reg_2649;
wire   [10:0] tmp18_fu_1775_p2;
reg   [10:0] tmp18_reg_2655;
wire   [9:0] tmp20_fu_1781_p2;
reg   [9:0] tmp20_reg_2660;
wire   [7:0] tmp21_fu_1787_p2;
reg   [7:0] tmp21_reg_2665;
wire   [7:0] tmp23_fu_1793_p2;
reg   [7:0] tmp23_reg_2670;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter1_state5;
wire   [9:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [7:0] k_buf_0_val_3_q0;
wire   [9:0] k_buf_0_val_3_address1;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [9:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [7:0] k_buf_0_val_4_q0;
wire   [9:0] k_buf_0_val_4_address1;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [9:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
wire   [9:0] k_buf_0_val_5_address1;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
wire   [9:0] k_buf_1_val_3_address0;
reg    k_buf_1_val_3_ce0;
wire   [7:0] k_buf_1_val_3_q0;
wire   [9:0] k_buf_1_val_3_address1;
reg    k_buf_1_val_3_ce1;
reg    k_buf_1_val_3_we1;
wire   [9:0] k_buf_1_val_4_address0;
reg    k_buf_1_val_4_ce0;
wire   [7:0] k_buf_1_val_4_q0;
wire   [9:0] k_buf_1_val_4_address1;
reg    k_buf_1_val_4_ce1;
reg    k_buf_1_val_4_we1;
reg   [7:0] k_buf_1_val_4_d1;
wire   [9:0] k_buf_1_val_5_address0;
reg    k_buf_1_val_5_ce0;
wire   [7:0] k_buf_1_val_5_q0;
wire   [9:0] k_buf_1_val_5_address1;
reg    k_buf_1_val_5_ce1;
reg    k_buf_1_val_5_we1;
reg   [7:0] k_buf_1_val_5_d1;
wire   [9:0] k_buf_2_val_3_address0;
reg    k_buf_2_val_3_ce0;
wire   [7:0] k_buf_2_val_3_q0;
wire   [9:0] k_buf_2_val_3_address1;
reg    k_buf_2_val_3_ce1;
reg    k_buf_2_val_3_we1;
wire   [9:0] k_buf_2_val_4_address0;
reg    k_buf_2_val_4_ce0;
wire   [7:0] k_buf_2_val_4_q0;
wire   [9:0] k_buf_2_val_4_address1;
reg    k_buf_2_val_4_ce1;
reg    k_buf_2_val_4_we1;
reg   [7:0] k_buf_2_val_4_d1;
wire   [9:0] k_buf_2_val_5_address0;
reg    k_buf_2_val_5_ce0;
wire   [7:0] k_buf_2_val_5_q0;
wire   [9:0] k_buf_2_val_5_address1;
reg    k_buf_2_val_5_ce1;
reg    k_buf_2_val_5_we1;
reg   [7:0] k_buf_2_val_5_d1;
reg   [1:0] tmp_5_reg_508;
wire   [0:0] tmp_7_fu_547_p2;
reg   [8:0] t_V_reg_519;
wire    ap_CS_fsm_state7;
wire   [63:0] tmp_25_fu_972_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] src_kernel_win_0_va_fu_166;
wire   [7:0] src_kernel_win_0_va_6_fu_1129_p3;
reg   [7:0] src_kernel_win_0_va_1_fu_170;
reg   [7:0] src_kernel_win_0_va_2_fu_174;
reg   [7:0] src_kernel_win_0_va_3_fu_178;
reg   [7:0] src_kernel_win_0_va_4_fu_182;
wire   [7:0] src_kernel_win_0_va_8_fu_1165_p3;
reg   [7:0] src_kernel_win_0_va_5_fu_186;
reg   [7:0] src_kernel_win_1_va_fu_190;
wire   [7:0] src_kernel_win_1_va_6_fu_1400_p3;
reg   [7:0] src_kernel_win_1_va_1_fu_194;
reg   [7:0] src_kernel_win_1_va_2_fu_198;
reg   [7:0] src_kernel_win_1_va_3_fu_202;
reg   [7:0] src_kernel_win_1_va_4_fu_206;
wire   [7:0] src_kernel_win_1_va_8_fu_1436_p3;
reg   [7:0] src_kernel_win_1_va_5_fu_210;
reg   [7:0] src_kernel_win_2_va_fu_214;
wire   [7:0] src_kernel_win_2_va_9_fu_1653_p3;
reg   [7:0] src_kernel_win_2_va_1_fu_218;
reg   [7:0] src_kernel_win_2_va_2_fu_222;
reg   [7:0] src_kernel_win_2_va_3_fu_226;
reg   [7:0] src_kernel_win_2_va_4_fu_230;
wire   [7:0] src_kernel_win_2_va_11_fu_1689_p3;
reg   [7:0] src_kernel_win_2_va_5_fu_234;
reg   [7:0] right_border_buf_0_s_fu_238;
wire   [7:0] col_buf_0_val_0_0_fu_1034_p3;
reg   [7:0] right_border_buf_0_1_fu_242;
reg   [7:0] right_border_buf_2_s_fu_246;
reg   [7:0] right_border_buf_0_2_fu_250;
wire   [7:0] col_buf_0_val_1_0_fu_1053_p3;
reg   [7:0] right_border_buf_0_3_fu_254;
reg   [7:0] right_border_buf_2_1_fu_258;
wire   [7:0] col_buf_2_val_2_0_fu_1605_p3;
reg   [7:0] right_border_buf_0_4_fu_262;
wire   [7:0] col_buf_0_val_2_0_fu_1072_p3;
reg   [7:0] right_border_buf_0_5_fu_266;
reg   [7:0] right_border_buf_2_2_fu_270;
reg   [7:0] right_border_buf_1_s_fu_274;
wire   [7:0] col_buf_1_val_0_0_fu_1305_p3;
reg   [7:0] right_border_buf_1_1_fu_278;
reg   [7:0] right_border_buf_2_3_fu_282;
wire   [7:0] col_buf_2_val_1_0_fu_1586_p3;
reg   [7:0] right_border_buf_1_2_fu_286;
wire   [7:0] col_buf_1_val_1_0_fu_1324_p3;
reg   [7:0] right_border_buf_1_3_fu_290;
reg   [7:0] right_border_buf_2_4_fu_294;
reg   [7:0] right_border_buf_1_4_fu_298;
wire   [7:0] col_buf_1_val_2_0_fu_1343_p3;
reg   [7:0] right_border_buf_1_5_fu_302;
reg   [7:0] right_border_buf_2_5_fu_306;
wire   [7:0] col_buf_2_val_0_0_fu_1567_p3;
wire   [7:0] tmp_fu_581_p4;
wire   [9:0] t_V_cast_fu_553_p1;
wire   [1:0] tmp_8_fu_615_p1;
wire   [9:0] tmp_3_fu_619_p2;
wire   [0:0] tmp_10_fu_631_p3;
wire   [0:0] tmp_4_fu_645_p2;
wire   [0:0] rev_fu_639_p2;
wire   [0:0] tmp_11_fu_657_p3;
wire   [9:0] p_assign_7_fu_665_p2;
wire   [9:0] p_p2_i498_i_fu_671_p3;
wire   [1:0] tmp_12_fu_679_p1;
wire   [9:0] p_assign_6_0_1_fu_695_p2;
wire   [9:0] p_assign_6_0_2_fu_721_p2;
wire   [0:0] tmp_13_fu_683_p2;
wire   [1:0] p_assign_8_fu_689_p2;
wire   [0:0] or_cond_i497_i_fu_651_p2;
wire   [1:0] tmp_139_cast_fu_625_p2;
wire   [1:0] p_p2_i498_i_0_p_assig_fu_747_p3;
wire   [1:0] y_fu_755_p3;
wire   [1:0] tmp_17_fu_717_p1;
wire   [0:0] tmp_15_fu_709_p3;
wire   [1:0] tmp_24_fu_775_p2;
wire   [1:0] tmp_30_fu_781_p1;
wire   [0:0] tmp_14_fu_701_p3;
wire   [1:0] tmp_31_fu_785_p3;
wire   [1:0] tmp_16_fu_769_p2;
wire   [1:0] tmp_32_fu_793_p3;
wire   [1:0] tmp_22_fu_743_p1;
wire   [0:0] tmp_20_fu_735_p3;
wire   [1:0] tmp_35_fu_813_p2;
wire   [1:0] tmp_38_fu_819_p1;
wire   [0:0] tmp_19_fu_727_p3;
wire   [1:0] tmp_39_fu_823_p3;
wire   [1:0] tmp_34_fu_807_p2;
wire   [1:0] tmp_36_fu_831_p3;
wire   [8:0] tmp_40_fu_861_p4;
wire   [10:0] t_V_2_cast_fu_845_p1;
wire   [10:0] ImagLoc_x_fu_877_p2;
wire   [0:0] tmp_41_fu_883_p3;
wire   [0:0] tmp_21_fu_897_p2;
wire   [0:0] rev1_fu_891_p2;
wire   [0:0] tmp_43_fu_909_p3;
wire   [10:0] p_assign_1_fu_917_p2;
wire   [10:0] p_p2_i_i_fu_923_p3;
wire   [0:0] tmp_23_fu_931_p2;
wire   [10:0] p_assign_2_fu_937_p2;
wire   [10:0] p_p2_i_i_p_assign_2_fu_943_p3;
wire  signed [10:0] x_fu_951_p3;
wire  signed [31:0] x_cast_fu_959_p1;
wire   [0:0] icmp1_fu_871_p2;
wire   [1:0] col_assign_2_0_t_fu_1017_p2;
wire   [7:0] tmp_26_fu_1022_p5;
wire   [7:0] tmp_27_fu_1041_p5;
wire   [7:0] tmp_28_fu_1060_p5;
wire   [7:0] tmp_29_fu_1118_p5;
wire   [7:0] tmp_33_fu_1136_p5;
wire   [7:0] tmp_37_fu_1154_p5;
wire   [8:0] tmp_157_0_0_2_cast_fu_1185_p1;
wire   [8:0] r_V_0_0_cast_fu_1181_p1;
wire  signed [8:0] sum_V_0_0_2_fu_1189_p2;
wire   [8:0] p_shl_fu_1199_p3;
wire   [9:0] p_shl_cast_fu_1207_p1;
wire  signed [9:0] r_V_10_0_1_fu_1211_p2;
wire   [8:0] r_V_0_2_cast_fu_1229_p1;
wire  signed [8:0] r_V_10_0_2_fu_1233_p2;
wire  signed [10:0] tmp_157_0_2_cast_fu_1239_p1;
wire  signed [10:0] tmp_157_0_1_cast_fu_1217_p1;
wire   [9:0] tmp_157_0_2_2_cast_c_fu_1247_p1;
wire  signed [9:0] sum_V_0_0_2_cast_cas_fu_1195_p1;
wire   [7:0] tmp_55_fu_1225_p1;
wire   [7:0] tmp_53_fu_1221_p1;
wire   [7:0] tmp_63_fu_1243_p1;
wire   [7:0] tmp_44_fu_1293_p5;
wire   [7:0] tmp_45_fu_1312_p5;
wire   [7:0] tmp_46_fu_1331_p5;
wire   [7:0] tmp_47_fu_1389_p5;
wire   [7:0] tmp_48_fu_1407_p5;
wire   [7:0] tmp_49_fu_1425_p5;
wire   [8:0] tmp_157_1_0_2_cast_fu_1456_p1;
wire   [8:0] r_V_1_0_cast_fu_1452_p1;
wire  signed [8:0] sum_V_1_0_2_fu_1460_p2;
wire   [8:0] p_shl1_fu_1470_p3;
wire   [9:0] p_shl1_cast_fu_1478_p1;
wire  signed [9:0] r_V_10_1_1_fu_1482_p2;
wire   [8:0] r_V_1_2_cast_fu_1500_p1;
wire  signed [8:0] r_V_10_1_2_fu_1504_p2;
wire  signed [10:0] tmp_157_1_2_cast_fu_1510_p1;
wire  signed [10:0] tmp_157_1_1_cast_fu_1488_p1;
wire   [9:0] tmp_157_1_2_2_cast_c_fu_1518_p1;
wire  signed [9:0] sum_V_1_0_2_cast_cas_fu_1466_p1;
wire   [7:0] tmp_70_fu_1496_p1;
wire   [7:0] tmp_69_fu_1492_p1;
wire   [7:0] tmp_72_fu_1514_p1;
wire   [7:0] tmp_56_fu_1555_p5;
wire   [7:0] tmp_57_fu_1574_p5;
wire   [7:0] tmp_58_fu_1593_p5;
wire   [7:0] tmp_59_fu_1642_p5;
wire   [7:0] tmp_60_fu_1660_p5;
wire   [7:0] tmp_61_fu_1678_p5;
wire   [8:0] tmp_157_2_0_2_cast_fu_1709_p1;
wire   [8:0] r_V_2_0_cast_fu_1705_p1;
wire  signed [8:0] sum_V_2_0_2_fu_1713_p2;
wire   [8:0] p_shl2_fu_1723_p3;
wire   [9:0] p_shl2_cast_fu_1731_p1;
wire  signed [9:0] r_V_10_2_1_fu_1735_p2;
wire   [8:0] r_V_2_2_cast_fu_1753_p1;
wire  signed [8:0] r_V_10_2_2_fu_1757_p2;
wire  signed [10:0] tmp_157_2_2_cast_fu_1763_p1;
wire  signed [10:0] tmp_157_2_1_cast_fu_1741_p1;
wire   [9:0] tmp_157_2_2_2_cast_c_fu_1771_p1;
wire  signed [9:0] sum_V_2_0_2_cast_cas_fu_1719_p1;
wire   [7:0] tmp_78_fu_1749_p1;
wire   [7:0] tmp_77_fu_1745_p1;
wire   [7:0] tmp_80_fu_1767_p1;
wire   [8:0] r_V_10_0_1_2_fu_1916_p3;
wire   [10:0] tmp_157_0_1_cast_66_fu_1923_p1;
wire  signed [10:0] tmp4_cast_fu_1932_p1;
wire   [10:0] tmp3_fu_1935_p2;
wire   [10:0] p_Val2_s_fu_1941_p2;
wire   [7:0] tmp_62_fu_1927_p2;
wire   [7:0] tmp6_fu_1954_p2;
wire   [0:0] p_Result_s_fu_1946_p3;
wire   [2:0] tmp_42_fu_1964_p4;
wire   [0:0] not_i_i_fu_1980_p2;
wire   [0:0] tmp_i_i_fu_1974_p2;
wire   [0:0] overflow_fu_1986_p2;
wire   [0:0] tmp_1_i_i_fu_2000_p2;
wire   [7:0] p_mux_i_i_cast_fu_1992_p3;
wire   [7:0] p_Val2_1_fu_1959_p2;
wire   [8:0] r_V_10_1_1_2_fu_2015_p3;
wire   [10:0] tmp_157_1_1_cast_67_fu_2022_p1;
wire  signed [10:0] tmp12_cast_fu_2031_p1;
wire   [10:0] tmp11_fu_2034_p2;
wire   [10:0] p_Val2_3_fu_2040_p2;
wire   [7:0] tmp_71_fu_2026_p2;
wire   [7:0] tmp14_fu_2053_p2;
wire   [0:0] p_Result_1_fu_2045_p3;
wire   [2:0] tmp_54_fu_2063_p4;
wire   [0:0] not_i_i1_fu_2079_p2;
wire   [0:0] tmp_i_i1_fu_2073_p2;
wire   [0:0] overflow_1_fu_2085_p2;
wire   [0:0] tmp_1_i_i1_fu_2099_p2;
wire   [7:0] p_mux_i_i30_cast_fu_2091_p3;
wire   [7:0] p_Val2_4_fu_2058_p2;
wire   [8:0] r_V_10_2_1_2_fu_2114_p3;
wire   [10:0] tmp_157_2_1_cast_68_fu_2121_p1;
wire  signed [10:0] tmp20_cast_fu_2130_p1;
wire   [10:0] tmp19_fu_2133_p2;
wire   [10:0] p_Val2_6_fu_2139_p2;
wire   [7:0] tmp_79_fu_2125_p2;
wire   [7:0] tmp22_fu_2152_p2;
wire   [0:0] p_Result_2_fu_2144_p3;
wire   [2:0] tmp_64_fu_2162_p4;
wire   [0:0] not_i_i2_fu_2178_p2;
wire   [0:0] tmp_i_i2_fu_2172_p2;
wire   [0:0] overflow_2_fu_2184_p2;
wire   [0:0] tmp_1_i_i2_fu_2198_p2;
wire   [7:0] p_mux_i_i39_cast_fu_2190_p3;
wire   [7:0] p_Val2_7_fu_2157_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_enable_operation_144;
reg    ap_enable_state4_pp0_iter0_stage0;
reg    ap_enable_operation_200;
reg    ap_enable_state5_pp0_iter1_stage0;
reg    ap_predicate_op215_store_state5;
reg    ap_enable_operation_215;
reg    ap_predicate_op223_store_state5;
reg    ap_enable_operation_223;
reg    ap_enable_operation_146;
reg    ap_enable_operation_204;
reg    ap_predicate_op213_store_state5;
reg    ap_enable_operation_213;
reg    ap_predicate_op221_store_state5;
reg    ap_enable_operation_221;
reg    ap_enable_operation_148;
reg    ap_enable_operation_207;
reg    ap_predicate_op211_store_state5;
reg    ap_enable_operation_211;
reg    ap_predicate_op220_store_state5;
reg    ap_enable_operation_220;
reg    ap_enable_operation_159;
reg    ap_enable_operation_265;
reg    ap_predicate_op279_store_state5;
reg    ap_enable_operation_279;
reg    ap_predicate_op287_store_state5;
reg    ap_enable_operation_287;
reg    ap_enable_operation_161;
reg    ap_enable_operation_268;
reg    ap_predicate_op277_store_state5;
reg    ap_enable_operation_277;
reg    ap_predicate_op285_store_state5;
reg    ap_enable_operation_285;
reg    ap_enable_operation_163;
reg    ap_enable_operation_271;
reg    ap_predicate_op275_store_state5;
reg    ap_enable_operation_275;
reg    ap_predicate_op284_store_state5;
reg    ap_enable_operation_284;
reg    ap_enable_operation_173;
reg    ap_enable_operation_326;
reg    ap_predicate_op340_store_state5;
reg    ap_enable_operation_340;
reg    ap_predicate_op345_store_state5;
reg    ap_enable_operation_345;
reg    ap_enable_operation_175;
reg    ap_enable_operation_329;
reg    ap_predicate_op338_store_state5;
reg    ap_enable_operation_338;
reg    ap_predicate_op343_store_state5;
reg    ap_enable_operation_343;
reg    ap_enable_operation_177;
reg    ap_enable_operation_332;
reg    ap_predicate_op336_store_state5;
reg    ap_enable_operation_336;
reg    ap_predicate_op342_store_state5;
reg    ap_enable_operation_342;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_1543;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_address1),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(p_src_data_stream_0_V_dout)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .q0(k_buf_0_val_4_q0),
    .address1(k_buf_0_val_4_address1),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_4_d1)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_address1),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_5_d1)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
k_buf_1_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_3_address0),
    .ce0(k_buf_1_val_3_ce0),
    .q0(k_buf_1_val_3_q0),
    .address1(k_buf_1_val_3_address1),
    .ce1(k_buf_1_val_3_ce1),
    .we1(k_buf_1_val_3_we1),
    .d1(p_src_data_stream_1_V_dout)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
k_buf_1_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_4_address0),
    .ce0(k_buf_1_val_4_ce0),
    .q0(k_buf_1_val_4_q0),
    .address1(k_buf_1_val_4_address1),
    .ce1(k_buf_1_val_4_ce1),
    .we1(k_buf_1_val_4_we1),
    .d1(k_buf_1_val_4_d1)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
k_buf_1_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_5_address0),
    .ce0(k_buf_1_val_5_ce0),
    .q0(k_buf_1_val_5_q0),
    .address1(k_buf_1_val_5_address1),
    .ce1(k_buf_1_val_5_ce1),
    .we1(k_buf_1_val_5_we1),
    .d1(k_buf_1_val_5_d1)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
k_buf_2_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_3_address0),
    .ce0(k_buf_2_val_3_ce0),
    .q0(k_buf_2_val_3_q0),
    .address1(k_buf_2_val_3_address1),
    .ce1(k_buf_2_val_3_ce1),
    .we1(k_buf_2_val_3_we1),
    .d1(p_src_data_stream_2_V_dout)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
k_buf_2_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_4_address0),
    .ce0(k_buf_2_val_4_ce0),
    .q0(k_buf_2_val_4_q0),
    .address1(k_buf_2_val_4_address1),
    .ce1(k_buf_2_val_4_ce1),
    .we1(k_buf_2_val_4_we1),
    .d1(k_buf_2_val_4_d1)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
k_buf_2_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_5_address0),
    .ce0(k_buf_2_val_5_ce0),
    .q0(k_buf_2_val_5_q0),
    .address1(k_buf_2_val_5_address1),
    .ce1(k_buf_2_val_5_ce1),
    .we1(k_buf_2_val_5_we1),
    .d1(k_buf_2_val_5_d1)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U31(
    .din0(right_border_buf_0_s_fu_238),
    .din1(right_border_buf_0_1_fu_242),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1017_p2),
    .dout(tmp_26_fu_1022_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U32(
    .din0(right_border_buf_0_2_fu_250),
    .din1(right_border_buf_0_3_fu_254),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1017_p2),
    .dout(tmp_27_fu_1041_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U33(
    .din0(right_border_buf_0_4_fu_262),
    .din1(right_border_buf_0_5_fu_266),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1017_p2),
    .dout(tmp_28_fu_1060_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U34(
    .din0(col_buf_0_val_0_0_fu_1034_p3),
    .din1(col_buf_0_val_1_0_fu_1053_p3),
    .din2(col_buf_0_val_2_0_fu_1072_p3),
    .din3(row_assign_9_0_0_t_reg_2487),
    .dout(tmp_29_fu_1118_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U35(
    .din0(col_buf_0_val_0_0_fu_1034_p3),
    .din1(col_buf_0_val_1_0_fu_1053_p3),
    .din2(col_buf_0_val_2_0_fu_1072_p3),
    .din3(row_assign_9_0_1_t_reg_2494),
    .dout(tmp_33_fu_1136_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U36(
    .din0(col_buf_0_val_0_0_fu_1034_p3),
    .din1(col_buf_0_val_1_0_fu_1053_p3),
    .din2(col_buf_0_val_2_0_fu_1072_p3),
    .din3(row_assign_9_0_2_t_reg_2501),
    .dout(tmp_37_fu_1154_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U37(
    .din0(right_border_buf_1_s_fu_274),
    .din1(right_border_buf_1_1_fu_278),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1017_p2),
    .dout(tmp_44_fu_1293_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U38(
    .din0(right_border_buf_1_2_fu_286),
    .din1(right_border_buf_1_3_fu_290),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1017_p2),
    .dout(tmp_45_fu_1312_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U39(
    .din0(right_border_buf_1_4_fu_298),
    .din1(right_border_buf_1_5_fu_302),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1017_p2),
    .dout(tmp_46_fu_1331_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U40(
    .din0(col_buf_1_val_0_0_fu_1305_p3),
    .din1(col_buf_1_val_1_0_fu_1324_p3),
    .din2(col_buf_1_val_2_0_fu_1343_p3),
    .din3(row_assign_9_0_0_t_reg_2487),
    .dout(tmp_47_fu_1389_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U41(
    .din0(col_buf_1_val_0_0_fu_1305_p3),
    .din1(col_buf_1_val_1_0_fu_1324_p3),
    .din2(col_buf_1_val_2_0_fu_1343_p3),
    .din3(row_assign_9_0_1_t_reg_2494),
    .dout(tmp_48_fu_1407_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U42(
    .din0(col_buf_1_val_0_0_fu_1305_p3),
    .din1(col_buf_1_val_1_0_fu_1324_p3),
    .din2(col_buf_1_val_2_0_fu_1343_p3),
    .din3(row_assign_9_0_2_t_reg_2501),
    .dout(tmp_49_fu_1425_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U43(
    .din0(right_border_buf_2_5_fu_306),
    .din1(right_border_buf_2_4_fu_294),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1017_p2),
    .dout(tmp_56_fu_1555_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U44(
    .din0(right_border_buf_2_3_fu_282),
    .din1(right_border_buf_2_2_fu_270),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1017_p2),
    .dout(tmp_57_fu_1574_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U45(
    .din0(right_border_buf_2_1_fu_258),
    .din1(right_border_buf_2_s_fu_246),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1017_p2),
    .dout(tmp_58_fu_1593_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U46(
    .din0(col_buf_2_val_0_0_fu_1567_p3),
    .din1(col_buf_2_val_1_0_fu_1586_p3),
    .din2(col_buf_2_val_2_0_fu_1605_p3),
    .din3(row_assign_9_0_0_t_reg_2487),
    .dout(tmp_59_fu_1642_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U47(
    .din0(col_buf_2_val_0_0_fu_1567_p3),
    .din1(col_buf_2_val_1_0_fu_1586_p3),
    .din2(col_buf_2_val_2_0_fu_1605_p3),
    .din3(row_assign_9_0_1_t_reg_2494),
    .dout(tmp_60_fu_1660_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U48(
    .din0(col_buf_2_val_0_0_fu_1567_p3),
    .din1(col_buf_2_val_1_0_fu_1586_p3),
    .din2(col_buf_2_val_2_0_fu_1605_p3),
    .din3(row_assign_9_0_2_t_reg_2501),
    .dout(tmp_61_fu_1678_p5)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((exitcond461_i_fu_849_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((exitcond462_i_fu_557_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter1_state5)) | ((exitcond462_i_fu_557_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter1_state5))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((exitcond462_i_fu_557_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond461_i_fu_849_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_V_2_reg_530 <= j_V_fu_855_p2;
    end else if (((exitcond462_i_fu_557_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        t_V_2_reg_530 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_7_fu_547_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_reg_519 <= 9'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        t_V_reg_519 <= i_V_reg_2447;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_5_reg_508 <= 2'd0;
    end else if (((tmp_7_fu_547_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_5_reg_508 <= tmp_6_fu_541_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond461_i_fu_849_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        brmerge_reg_2526 <= brmerge_fu_967_p2;
        k_buf_0_val_3_addr_reg_2539 <= tmp_25_fu_972_p1;
        k_buf_0_val_4_addr_reg_2545 <= tmp_25_fu_972_p1;
        k_buf_0_val_5_addr_reg_2551 <= tmp_25_fu_972_p1;
        k_buf_1_val_3_addr_reg_2561 <= tmp_25_fu_972_p1;
        k_buf_1_val_4_addr_reg_2567 <= tmp_25_fu_972_p1;
        k_buf_1_val_5_addr_reg_2573 <= tmp_25_fu_972_p1;
        k_buf_2_val_3_addr_reg_2579 <= tmp_25_fu_972_p1;
        k_buf_2_val_4_addr_reg_2585 <= tmp_25_fu_972_p1;
        k_buf_2_val_5_addr_reg_2591 <= tmp_25_fu_972_p1;
        or_cond_i_i_reg_2517 <= or_cond_i_i_fu_903_p2;
        or_cond_i_reg_2557 <= or_cond_i_fu_985_p2;
        tmp_50_reg_2521 <= tmp_50_fu_963_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond461_i_reg_2508 <= exitcond461_i_fu_849_p2;
        or_cond_i_reg_2557_pp0_iter1_reg <= or_cond_i_reg_2557;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_V_reg_2447 <= i_V_fu_563_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond462_i_fu_557_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        icmp_reg_2461 <= icmp_fu_591_p2;
        row_assign_9_0_0_t_reg_2487 <= row_assign_9_0_0_t_fu_763_p2;
        row_assign_9_0_1_t_reg_2494 <= row_assign_9_0_1_t_fu_801_p2;
        row_assign_9_0_2_t_reg_2501 <= row_assign_9_0_2_t_fu_839_p2;
        tmp_115_0_1_reg_2470 <= tmp_115_0_1_fu_603_p2;
        tmp_1_reg_2452 <= tmp_1_fu_569_p2;
        tmp_2_reg_2474 <= tmp_2_fu_609_p2;
        tmp_71_0_0_not_reg_2456 <= tmp_71_0_0_not_fu_575_p2;
        tmp_9_reg_2466 <= tmp_9_fu_597_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        right_border_buf_0_1_fu_242 <= right_border_buf_0_s_fu_238;
        right_border_buf_0_2_fu_250 <= col_buf_0_val_1_0_fu_1053_p3;
        right_border_buf_0_3_fu_254 <= right_border_buf_0_2_fu_250;
        right_border_buf_0_4_fu_262 <= col_buf_0_val_2_0_fu_1072_p3;
        right_border_buf_0_5_fu_266 <= right_border_buf_0_4_fu_262;
        right_border_buf_0_s_fu_238 <= col_buf_0_val_0_0_fu_1034_p3;
        right_border_buf_1_1_fu_278 <= right_border_buf_1_s_fu_274;
        right_border_buf_1_2_fu_286 <= col_buf_1_val_1_0_fu_1324_p3;
        right_border_buf_1_3_fu_290 <= right_border_buf_1_2_fu_286;
        right_border_buf_1_4_fu_298 <= col_buf_1_val_2_0_fu_1343_p3;
        right_border_buf_1_5_fu_302 <= right_border_buf_1_4_fu_298;
        right_border_buf_1_s_fu_274 <= col_buf_1_val_0_0_fu_1305_p3;
        right_border_buf_2_1_fu_258 <= col_buf_2_val_2_0_fu_1605_p3;
        right_border_buf_2_2_fu_270 <= right_border_buf_2_3_fu_282;
        right_border_buf_2_3_fu_282 <= col_buf_2_val_1_0_fu_1586_p3;
        right_border_buf_2_4_fu_294 <= right_border_buf_2_5_fu_306;
        right_border_buf_2_5_fu_306 <= col_buf_2_val_0_0_fu_1567_p3;
        right_border_buf_2_s_fu_246 <= right_border_buf_2_1_fu_258;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_1_fu_170 <= src_kernel_win_0_va_fu_166;
        src_kernel_win_0_va_2_fu_174 <= src_kernel_win_0_va_7_fu_1147_p3;
        src_kernel_win_0_va_3_fu_178 <= src_kernel_win_0_va_2_fu_174;
        src_kernel_win_0_va_4_fu_182 <= src_kernel_win_0_va_8_fu_1165_p3;
        src_kernel_win_0_va_5_fu_186 <= src_kernel_win_0_va_4_fu_182;
        src_kernel_win_0_va_fu_166 <= src_kernel_win_0_va_6_fu_1129_p3;
        src_kernel_win_1_va_1_fu_194 <= src_kernel_win_1_va_fu_190;
        src_kernel_win_1_va_2_fu_198 <= src_kernel_win_1_va_7_fu_1418_p3;
        src_kernel_win_1_va_3_fu_202 <= src_kernel_win_1_va_2_fu_198;
        src_kernel_win_1_va_4_fu_206 <= src_kernel_win_1_va_8_fu_1436_p3;
        src_kernel_win_1_va_5_fu_210 <= src_kernel_win_1_va_4_fu_206;
        src_kernel_win_1_va_fu_190 <= src_kernel_win_1_va_6_fu_1400_p3;
        src_kernel_win_2_va_1_fu_218 <= src_kernel_win_2_va_fu_214;
        src_kernel_win_2_va_2_fu_222 <= src_kernel_win_2_va_10_fu_1671_p3;
        src_kernel_win_2_va_3_fu_226 <= src_kernel_win_2_va_2_fu_222;
        src_kernel_win_2_va_4_fu_230 <= src_kernel_win_2_va_11_fu_1689_p3;
        src_kernel_win_2_va_5_fu_234 <= src_kernel_win_2_va_4_fu_230;
        src_kernel_win_2_va_fu_214 <= src_kernel_win_2_va_9_fu_1653_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond461_i_reg_2508 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_7_reg_2597 <= src_kernel_win_0_va_7_fu_1147_p3;
        src_kernel_win_1_va_7_reg_2623 <= src_kernel_win_1_va_7_fu_1418_p3;
        src_kernel_win_2_va_10_reg_2649 <= src_kernel_win_2_va_10_fu_1671_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_2557 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp10_reg_2629 <= tmp10_fu_1522_p2;
        tmp12_reg_2634 <= tmp12_fu_1528_p2;
        tmp13_reg_2639 <= tmp13_fu_1534_p2;
        tmp15_reg_2644 <= tmp15_fu_1540_p2;
        tmp18_reg_2655 <= tmp18_fu_1775_p2;
        tmp20_reg_2660 <= tmp20_fu_1781_p2;
        tmp21_reg_2665 <= tmp21_fu_1787_p2;
        tmp23_reg_2670 <= tmp23_fu_1793_p2;
        tmp2_reg_2603 <= tmp2_fu_1251_p2;
        tmp4_reg_2608 <= tmp4_fu_1257_p2;
        tmp5_reg_2613 <= tmp5_fu_1263_p2;
        tmp7_reg_2618 <= tmp7_fu_1269_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_condition_pp0_exit_iter1_state5 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter1_state5 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((exitcond462_i_fu_557_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond462_i_fu_557_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2466 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2466 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_115_0_1_reg_2470 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1543)) begin
        if (((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1))) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0;
        end else if (((tmp_115_0_1_reg_2470 == 1'd1) & (icmp_reg_2461 == 1'd0))) begin
            k_buf_0_val_4_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_115_0_1_reg_2470 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2466 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1543)) begin
        if (((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1))) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0;
        end else if (((tmp_9_reg_2466 == 1'd1) & (icmp_reg_2461 == 1'd0))) begin
            k_buf_0_val_5_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2466 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_3_ce0 = 1'b1;
    end else begin
        k_buf_1_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2466 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_3_ce1 = 1'b1;
    end else begin
        k_buf_1_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2466 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_3_we1 = 1'b1;
    end else begin
        k_buf_1_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_4_ce0 = 1'b1;
    end else begin
        k_buf_1_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_115_0_1_reg_2470 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_4_ce1 = 1'b1;
    end else begin
        k_buf_1_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1543)) begin
        if (((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1))) begin
            k_buf_1_val_4_d1 = k_buf_1_val_3_q0;
        end else if (((tmp_115_0_1_reg_2470 == 1'd1) & (icmp_reg_2461 == 1'd0))) begin
            k_buf_1_val_4_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_115_0_1_reg_2470 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_4_we1 = 1'b1;
    end else begin
        k_buf_1_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_5_ce0 = 1'b1;
    end else begin
        k_buf_1_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2466 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_5_ce1 = 1'b1;
    end else begin
        k_buf_1_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1543)) begin
        if (((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1))) begin
            k_buf_1_val_5_d1 = k_buf_1_val_4_q0;
        end else if (((tmp_9_reg_2466 == 1'd1) & (icmp_reg_2461 == 1'd0))) begin
            k_buf_1_val_5_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2466 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_5_we1 = 1'b1;
    end else begin
        k_buf_1_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_3_ce0 = 1'b1;
    end else begin
        k_buf_2_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2466 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_3_ce1 = 1'b1;
    end else begin
        k_buf_2_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2466 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_3_we1 = 1'b1;
    end else begin
        k_buf_2_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_4_ce0 = 1'b1;
    end else begin
        k_buf_2_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_115_0_1_reg_2470 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_4_ce1 = 1'b1;
    end else begin
        k_buf_2_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1543)) begin
        if (((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1))) begin
            k_buf_2_val_4_d1 = k_buf_2_val_3_q0;
        end else if (((tmp_115_0_1_reg_2470 == 1'd1) & (icmp_reg_2461 == 1'd0))) begin
            k_buf_2_val_4_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_115_0_1_reg_2470 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_4_we1 = 1'b1;
    end else begin
        k_buf_2_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_5_ce0 = 1'b1;
    end else begin
        k_buf_2_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2466 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_5_ce1 = 1'b1;
    end else begin
        k_buf_2_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1543)) begin
        if (((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1))) begin
            k_buf_2_val_5_d1 = k_buf_2_val_4_q0;
        end else if (((tmp_9_reg_2466 == 1'd1) & (icmp_reg_2461 == 1'd0))) begin
            k_buf_2_val_5_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2466 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_5_we1 = 1'b1;
    end else begin
        k_buf_2_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2557_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_dst_data_stream_0_V_blk_n = p_dst_data_stream_0_V_full_n;
    end else begin
        p_dst_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2557_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_0_V_write = 1'b1;
    end else begin
        p_dst_data_stream_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2557_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_dst_data_stream_1_V_blk_n = p_dst_data_stream_1_V_full_n;
    end else begin
        p_dst_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2557_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_1_V_write = 1'b1;
    end else begin
        p_dst_data_stream_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2557_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_dst_data_stream_2_V_blk_n = p_dst_data_stream_2_V_full_n;
    end else begin
        p_dst_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2557_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_2_V_write = 1'b1;
    end else begin
        p_dst_data_stream_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_0_V_blk_n = p_src_data_stream_0_V_empty_n;
    end else begin
        p_src_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op222_read_state5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op210_read_state5 == 1'b1)))) begin
        p_src_data_stream_0_V_read = 1'b1;
    end else begin
        p_src_data_stream_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_1_V_blk_n = p_src_data_stream_1_V_empty_n;
    end else begin
        p_src_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op286_read_state5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op274_read_state5 == 1'b1)))) begin
        p_src_data_stream_1_V_read = 1'b1;
    end else begin
        p_src_data_stream_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_2_V_blk_n = p_src_data_stream_2_V_empty_n;
    end else begin
        p_src_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op344_read_state5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op335_read_state5 == 1'b1)))) begin
        p_src_data_stream_2_V_read = 1'b1;
    end else begin
        p_src_data_stream_2_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_7_fu_547_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((exitcond462_i_fu_557_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_fu_877_p2 = ($signed(11'd2047) + $signed(t_V_2_cast_fu_845_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (((or_cond_i_reg_2557_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2557_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2557_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op344_read_state5 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op335_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op286_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op274_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op222_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op210_read_state5 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (((or_cond_i_reg_2557_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2557_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2557_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op344_read_state5 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op335_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op286_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op274_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op222_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op210_read_state5 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (((or_cond_i_reg_2557_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2557_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2557_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op344_read_state5 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op335_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op286_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op274_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op222_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op210_read_state5 == 1'b1)))));
end

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter1 = (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op344_read_state5 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op335_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op286_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op274_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op222_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op210_read_state5 == 1'b1)));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter2 = (((or_cond_i_reg_2557_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2557_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2557_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_1543 = ((or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_operation_144 = (exitcond461_i_fu_849_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_146 = (exitcond461_i_fu_849_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_148 = (exitcond461_i_fu_849_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_159 = (exitcond461_i_fu_849_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_161 = (exitcond461_i_fu_849_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_163 = (exitcond461_i_fu_849_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_173 = (exitcond461_i_fu_849_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_175 = (exitcond461_i_fu_849_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_177 = (exitcond461_i_fu_849_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_200 = (exitcond461_i_reg_2508 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_204 = (exitcond461_i_reg_2508 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_207 = (exitcond461_i_reg_2508 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_211 = (ap_predicate_op211_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_213 = (ap_predicate_op213_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_215 = (ap_predicate_op215_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_220 = (ap_predicate_op220_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_221 = (ap_predicate_op221_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_223 = (ap_predicate_op223_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_265 = (exitcond461_i_reg_2508 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_268 = (exitcond461_i_reg_2508 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_271 = (exitcond461_i_reg_2508 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_275 = (ap_predicate_op275_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_277 = (ap_predicate_op277_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_279 = (ap_predicate_op279_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_284 = (ap_predicate_op284_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_285 = (ap_predicate_op285_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_287 = (ap_predicate_op287_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_326 = (exitcond461_i_reg_2508 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_329 = (exitcond461_i_reg_2508 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_332 = (exitcond461_i_reg_2508 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_336 = (ap_predicate_op336_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_338 = (ap_predicate_op338_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_340 = (ap_predicate_op340_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_342 = (ap_predicate_op342_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_343 = (ap_predicate_op343_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_345 = (ap_predicate_op345_store_state5 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_enable_state4_pp0_iter0_stage0 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_enable_state5_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_predicate_op210_read_state5 = ((or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0));
end

always @ (*) begin
    ap_predicate_op211_store_state5 = ((tmp_9_reg_2466 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0));
end

always @ (*) begin
    ap_predicate_op213_store_state5 = ((tmp_115_0_1_reg_2470 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0));
end

always @ (*) begin
    ap_predicate_op215_store_state5 = ((tmp_9_reg_2466 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0));
end

always @ (*) begin
    ap_predicate_op220_store_state5 = ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0));
end

always @ (*) begin
    ap_predicate_op221_store_state5 = ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0));
end

always @ (*) begin
    ap_predicate_op222_read_state5 = ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0));
end

always @ (*) begin
    ap_predicate_op223_store_state5 = ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0));
end

always @ (*) begin
    ap_predicate_op274_read_state5 = ((or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0));
end

always @ (*) begin
    ap_predicate_op275_store_state5 = ((tmp_9_reg_2466 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0));
end

always @ (*) begin
    ap_predicate_op277_store_state5 = ((tmp_115_0_1_reg_2470 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0));
end

always @ (*) begin
    ap_predicate_op279_store_state5 = ((tmp_9_reg_2466 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0));
end

always @ (*) begin
    ap_predicate_op284_store_state5 = ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0));
end

always @ (*) begin
    ap_predicate_op285_store_state5 = ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0));
end

always @ (*) begin
    ap_predicate_op286_read_state5 = ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0));
end

always @ (*) begin
    ap_predicate_op287_store_state5 = ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0));
end

always @ (*) begin
    ap_predicate_op335_read_state5 = ((or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0));
end

always @ (*) begin
    ap_predicate_op336_store_state5 = ((tmp_9_reg_2466 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0));
end

always @ (*) begin
    ap_predicate_op338_store_state5 = ((tmp_115_0_1_reg_2470 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0));
end

always @ (*) begin
    ap_predicate_op340_store_state5 = ((tmp_9_reg_2466 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (icmp_reg_2461 == 1'd0) & (exitcond461_i_reg_2508 == 1'd0));
end

always @ (*) begin
    ap_predicate_op342_store_state5 = ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0));
end

always @ (*) begin
    ap_predicate_op343_store_state5 = ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0));
end

always @ (*) begin
    ap_predicate_op344_read_state5 = ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0));
end

always @ (*) begin
    ap_predicate_op345_store_state5 = ((tmp_1_reg_2452 == 1'd1) & (icmp_reg_2461 == 1'd1) & (or_cond_i_i_reg_2517 == 1'd1) & (exitcond461_i_reg_2508 == 1'd0));
end

assign brmerge_fu_967_p2 = (tmp_71_0_0_not_reg_2456 | tmp_21_fu_897_p2);

assign col_assign_2_0_t_fu_1017_p2 = (tmp_50_reg_2521 ^ 2'd3);

assign col_buf_0_val_0_0_fu_1034_p3 = ((brmerge_reg_2526[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_26_fu_1022_p5);

assign col_buf_0_val_1_0_fu_1053_p3 = ((brmerge_reg_2526[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_27_fu_1041_p5);

assign col_buf_0_val_2_0_fu_1072_p3 = ((brmerge_reg_2526[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_28_fu_1060_p5);

assign col_buf_1_val_0_0_fu_1305_p3 = ((brmerge_reg_2526[0:0] === 1'b1) ? k_buf_1_val_3_q0 : tmp_44_fu_1293_p5);

assign col_buf_1_val_1_0_fu_1324_p3 = ((brmerge_reg_2526[0:0] === 1'b1) ? k_buf_1_val_4_q0 : tmp_45_fu_1312_p5);

assign col_buf_1_val_2_0_fu_1343_p3 = ((brmerge_reg_2526[0:0] === 1'b1) ? k_buf_1_val_5_q0 : tmp_46_fu_1331_p5);

assign col_buf_2_val_0_0_fu_1567_p3 = ((brmerge_reg_2526[0:0] === 1'b1) ? k_buf_2_val_3_q0 : tmp_56_fu_1555_p5);

assign col_buf_2_val_1_0_fu_1586_p3 = ((brmerge_reg_2526[0:0] === 1'b1) ? k_buf_2_val_4_q0 : tmp_57_fu_1574_p5);

assign col_buf_2_val_2_0_fu_1605_p3 = ((brmerge_reg_2526[0:0] === 1'b1) ? k_buf_2_val_5_q0 : tmp_58_fu_1593_p5);

assign exitcond461_i_fu_849_p2 = ((t_V_2_reg_530 == 10'd642) ? 1'b1 : 1'b0);

assign exitcond462_i_fu_557_p2 = ((t_V_reg_519 == 9'd482) ? 1'b1 : 1'b0);

assign i_V_fu_563_p2 = (t_V_reg_519 + 9'd1);

assign icmp1_fu_871_p2 = ((tmp_40_fu_861_p4 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_fu_591_p2 = ((tmp_fu_581_p4 != 8'd0) ? 1'b1 : 1'b0);

assign j_V_fu_855_p2 = (t_V_2_reg_530 + 10'd1);

assign k_buf_0_val_3_address0 = tmp_25_fu_972_p1;

assign k_buf_0_val_3_address1 = k_buf_0_val_3_addr_reg_2539;

assign k_buf_0_val_4_address0 = tmp_25_fu_972_p1;

assign k_buf_0_val_4_address1 = k_buf_0_val_4_addr_reg_2545;

assign k_buf_0_val_5_address0 = tmp_25_fu_972_p1;

assign k_buf_0_val_5_address1 = k_buf_0_val_5_addr_reg_2551;

assign k_buf_1_val_3_address0 = tmp_25_fu_972_p1;

assign k_buf_1_val_3_address1 = k_buf_1_val_3_addr_reg_2561;

assign k_buf_1_val_4_address0 = tmp_25_fu_972_p1;

assign k_buf_1_val_4_address1 = k_buf_1_val_4_addr_reg_2567;

assign k_buf_1_val_5_address0 = tmp_25_fu_972_p1;

assign k_buf_1_val_5_address1 = k_buf_1_val_5_addr_reg_2573;

assign k_buf_2_val_3_address0 = tmp_25_fu_972_p1;

assign k_buf_2_val_3_address1 = k_buf_2_val_3_addr_reg_2579;

assign k_buf_2_val_4_address0 = tmp_25_fu_972_p1;

assign k_buf_2_val_4_address1 = k_buf_2_val_4_addr_reg_2585;

assign k_buf_2_val_5_address0 = tmp_25_fu_972_p1;

assign k_buf_2_val_5_address1 = k_buf_2_val_5_addr_reg_2591;

assign not_i_i1_fu_2079_p2 = ((tmp_54_fu_2063_p4 != 3'd0) ? 1'b1 : 1'b0);

assign not_i_i2_fu_2178_p2 = ((tmp_64_fu_2162_p4 != 3'd0) ? 1'b1 : 1'b0);

assign not_i_i_fu_1980_p2 = ((tmp_42_fu_1964_p4 != 3'd0) ? 1'b1 : 1'b0);

assign or_cond_i497_i_fu_651_p2 = (tmp_4_fu_645_p2 & rev_fu_639_p2);

assign or_cond_i_fu_985_p2 = (icmp_reg_2461 & icmp1_fu_871_p2);

assign or_cond_i_i_fu_903_p2 = (tmp_21_fu_897_p2 & rev1_fu_891_p2);

assign overflow_1_fu_2085_p2 = (tmp_i_i1_fu_2073_p2 & not_i_i1_fu_2079_p2);

assign overflow_2_fu_2184_p2 = (tmp_i_i2_fu_2172_p2 & not_i_i2_fu_2178_p2);

assign overflow_fu_1986_p2 = (tmp_i_i_fu_1974_p2 & not_i_i_fu_1980_p2);

assign p_Result_1_fu_2045_p3 = p_Val2_3_fu_2040_p2[32'd10];

assign p_Result_2_fu_2144_p3 = p_Val2_6_fu_2139_p2[32'd10];

assign p_Result_s_fu_1946_p3 = p_Val2_s_fu_1941_p2[32'd10];

assign p_Val2_1_fu_1959_p2 = (tmp5_reg_2613 + tmp6_fu_1954_p2);

assign p_Val2_3_fu_2040_p2 = (tmp10_reg_2629 + tmp11_fu_2034_p2);

assign p_Val2_4_fu_2058_p2 = (tmp13_reg_2639 + tmp14_fu_2053_p2);

assign p_Val2_6_fu_2139_p2 = (tmp18_reg_2655 + tmp19_fu_2133_p2);

assign p_Val2_7_fu_2157_p2 = (tmp21_reg_2665 + tmp22_fu_2152_p2);

assign p_Val2_s_fu_1941_p2 = (tmp2_reg_2603 + tmp3_fu_1935_p2);

assign p_assign_1_fu_917_p2 = (11'd1 - t_V_2_cast_fu_845_p1);

assign p_assign_2_fu_937_p2 = ($signed(11'd1278) - $signed(p_p2_i_i_fu_923_p3));

assign p_assign_6_0_1_fu_695_p2 = ($signed(10'd1022) + $signed(t_V_cast_fu_553_p1));

assign p_assign_6_0_2_fu_721_p2 = ($signed(10'd1021) + $signed(t_V_cast_fu_553_p1));

assign p_assign_7_fu_665_p2 = (10'd1 - t_V_cast_fu_553_p1);

assign p_assign_8_fu_689_p2 = ($signed(2'd2) - $signed(tmp_12_fu_679_p1));

assign p_dst_data_stream_0_V_din = ((tmp_1_i_i_fu_2000_p2[0:0] === 1'b1) ? p_mux_i_i_cast_fu_1992_p3 : p_Val2_1_fu_1959_p2);

assign p_dst_data_stream_1_V_din = ((tmp_1_i_i1_fu_2099_p2[0:0] === 1'b1) ? p_mux_i_i30_cast_fu_2091_p3 : p_Val2_4_fu_2058_p2);

assign p_dst_data_stream_2_V_din = ((tmp_1_i_i2_fu_2198_p2[0:0] === 1'b1) ? p_mux_i_i39_cast_fu_2190_p3 : p_Val2_7_fu_2157_p2);

assign p_mux_i_i30_cast_fu_2091_p3 = ((tmp_i_i1_fu_2073_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_mux_i_i39_cast_fu_2190_p3 = ((tmp_i_i2_fu_2172_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_mux_i_i_cast_fu_1992_p3 = ((tmp_i_i_fu_1974_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_p2_i498_i_0_p_assig_fu_747_p3 = ((tmp_13_fu_683_p2[0:0] === 1'b1) ? tmp_12_fu_679_p1 : p_assign_8_fu_689_p2);

assign p_p2_i498_i_fu_671_p3 = ((tmp_11_fu_657_p3[0:0] === 1'b1) ? p_assign_7_fu_665_p2 : tmp_3_fu_619_p2);

assign p_p2_i_i_fu_923_p3 = ((tmp_43_fu_909_p3[0:0] === 1'b1) ? p_assign_1_fu_917_p2 : ImagLoc_x_fu_877_p2);

assign p_p2_i_i_p_assign_2_fu_943_p3 = ((tmp_23_fu_931_p2[0:0] === 1'b1) ? p_p2_i_i_fu_923_p3 : p_assign_2_fu_937_p2);

assign p_shl1_cast_fu_1478_p1 = p_shl1_fu_1470_p3;

assign p_shl1_fu_1470_p3 = {{src_kernel_win_1_va_3_fu_202}, {1'd0}};

assign p_shl2_cast_fu_1731_p1 = p_shl2_fu_1723_p3;

assign p_shl2_fu_1723_p3 = {{src_kernel_win_2_va_3_fu_226}, {1'd0}};

assign p_shl_cast_fu_1207_p1 = p_shl_fu_1199_p3;

assign p_shl_fu_1199_p3 = {{src_kernel_win_0_va_3_fu_178}, {1'd0}};

assign r_V_0_0_cast_fu_1181_p1 = src_kernel_win_0_va_5_fu_186;

assign r_V_0_2_cast_fu_1229_p1 = src_kernel_win_0_va_1_fu_170;

assign r_V_10_0_1_2_fu_1916_p3 = {{src_kernel_win_0_va_7_reg_2597}, {1'd0}};

assign r_V_10_0_1_fu_1211_p2 = (10'd0 - p_shl_cast_fu_1207_p1);

assign r_V_10_0_2_fu_1233_p2 = (9'd0 - r_V_0_2_cast_fu_1229_p1);

assign r_V_10_1_1_2_fu_2015_p3 = {{src_kernel_win_1_va_7_reg_2623}, {1'd0}};

assign r_V_10_1_1_fu_1482_p2 = (10'd0 - p_shl1_cast_fu_1478_p1);

assign r_V_10_1_2_fu_1504_p2 = (9'd0 - r_V_1_2_cast_fu_1500_p1);

assign r_V_10_2_1_2_fu_2114_p3 = {{src_kernel_win_2_va_10_reg_2649}, {1'd0}};

assign r_V_10_2_1_fu_1735_p2 = (10'd0 - p_shl2_cast_fu_1731_p1);

assign r_V_10_2_2_fu_1757_p2 = (9'd0 - r_V_2_2_cast_fu_1753_p1);

assign r_V_1_0_cast_fu_1452_p1 = src_kernel_win_1_va_5_fu_210;

assign r_V_1_2_cast_fu_1500_p1 = src_kernel_win_1_va_1_fu_194;

assign r_V_2_0_cast_fu_1705_p1 = src_kernel_win_2_va_5_fu_234;

assign r_V_2_2_cast_fu_1753_p1 = src_kernel_win_2_va_1_fu_218;

assign rev1_fu_891_p2 = (tmp_41_fu_883_p3 ^ 1'd1);

assign rev_fu_639_p2 = (tmp_10_fu_631_p3 ^ 1'd1);

assign row_assign_9_0_0_t_fu_763_p2 = (y_fu_755_p3 ^ 2'd3);

assign row_assign_9_0_1_t_fu_801_p2 = (tmp_32_fu_793_p3 ^ 2'd3);

assign row_assign_9_0_2_t_fu_839_p2 = (tmp_36_fu_831_p3 ^ 2'd3);

assign src_kernel_win_0_va_6_fu_1129_p3 = ((tmp_2_reg_2474[0:0] === 1'b1) ? tmp_29_fu_1118_p5 : col_buf_0_val_0_0_fu_1034_p3);

assign src_kernel_win_0_va_7_fu_1147_p3 = ((tmp_2_reg_2474[0:0] === 1'b1) ? tmp_33_fu_1136_p5 : col_buf_0_val_1_0_fu_1053_p3);

assign src_kernel_win_0_va_8_fu_1165_p3 = ((tmp_2_reg_2474[0:0] === 1'b1) ? tmp_37_fu_1154_p5 : col_buf_0_val_2_0_fu_1072_p3);

assign src_kernel_win_1_va_6_fu_1400_p3 = ((tmp_2_reg_2474[0:0] === 1'b1) ? tmp_47_fu_1389_p5 : col_buf_1_val_0_0_fu_1305_p3);

assign src_kernel_win_1_va_7_fu_1418_p3 = ((tmp_2_reg_2474[0:0] === 1'b1) ? tmp_48_fu_1407_p5 : col_buf_1_val_1_0_fu_1324_p3);

assign src_kernel_win_1_va_8_fu_1436_p3 = ((tmp_2_reg_2474[0:0] === 1'b1) ? tmp_49_fu_1425_p5 : col_buf_1_val_2_0_fu_1343_p3);

assign src_kernel_win_2_va_10_fu_1671_p3 = ((tmp_2_reg_2474[0:0] === 1'b1) ? tmp_60_fu_1660_p5 : col_buf_2_val_1_0_fu_1586_p3);

assign src_kernel_win_2_va_11_fu_1689_p3 = ((tmp_2_reg_2474[0:0] === 1'b1) ? tmp_61_fu_1678_p5 : col_buf_2_val_2_0_fu_1605_p3);

assign src_kernel_win_2_va_9_fu_1653_p3 = ((tmp_2_reg_2474[0:0] === 1'b1) ? tmp_59_fu_1642_p5 : col_buf_2_val_0_0_fu_1567_p3);

assign sum_V_0_0_2_cast_cas_fu_1195_p1 = sum_V_0_0_2_fu_1189_p2;

assign sum_V_0_0_2_fu_1189_p2 = (tmp_157_0_0_2_cast_fu_1185_p1 - r_V_0_0_cast_fu_1181_p1);

assign sum_V_1_0_2_cast_cas_fu_1466_p1 = sum_V_1_0_2_fu_1460_p2;

assign sum_V_1_0_2_fu_1460_p2 = (tmp_157_1_0_2_cast_fu_1456_p1 - r_V_1_0_cast_fu_1452_p1);

assign sum_V_2_0_2_cast_cas_fu_1719_p1 = sum_V_2_0_2_fu_1713_p2;

assign sum_V_2_0_2_fu_1713_p2 = (tmp_157_2_0_2_cast_fu_1709_p1 - r_V_2_0_cast_fu_1705_p1);

assign t_V_2_cast_fu_845_p1 = t_V_2_reg_530;

assign t_V_cast_fu_553_p1 = t_V_reg_519;

assign tmp10_fu_1522_p2 = ($signed(tmp_157_1_2_cast_fu_1510_p1) + $signed(tmp_157_1_1_cast_fu_1488_p1));

assign tmp11_fu_2034_p2 = ($signed(tmp_157_1_1_cast_67_fu_2022_p1) + $signed(tmp12_cast_fu_2031_p1));

assign tmp12_cast_fu_2031_p1 = $signed(tmp12_reg_2634);

assign tmp12_fu_1528_p2 = ($signed(tmp_157_1_2_2_cast_c_fu_1518_p1) + $signed(sum_V_1_0_2_cast_cas_fu_1466_p1));

assign tmp13_fu_1534_p2 = (tmp_70_fu_1496_p1 + tmp_69_fu_1492_p1);

assign tmp14_fu_2053_p2 = (tmp_71_fu_2026_p2 + tmp15_reg_2644);

assign tmp15_fu_1540_p2 = (src_kernel_win_1_va_6_fu_1400_p3 + tmp_72_fu_1514_p1);

assign tmp18_fu_1775_p2 = ($signed(tmp_157_2_2_cast_fu_1763_p1) + $signed(tmp_157_2_1_cast_fu_1741_p1));

assign tmp19_fu_2133_p2 = ($signed(tmp_157_2_1_cast_68_fu_2121_p1) + $signed(tmp20_cast_fu_2130_p1));

assign tmp20_cast_fu_2130_p1 = $signed(tmp20_reg_2660);

assign tmp20_fu_1781_p2 = ($signed(tmp_157_2_2_2_cast_c_fu_1771_p1) + $signed(sum_V_2_0_2_cast_cas_fu_1719_p1));

assign tmp21_fu_1787_p2 = (tmp_78_fu_1749_p1 + tmp_77_fu_1745_p1);

assign tmp22_fu_2152_p2 = (tmp_79_fu_2125_p2 + tmp23_reg_2670);

assign tmp23_fu_1793_p2 = (src_kernel_win_2_va_9_fu_1653_p3 + tmp_80_fu_1767_p1);

assign tmp2_fu_1251_p2 = ($signed(tmp_157_0_2_cast_fu_1239_p1) + $signed(tmp_157_0_1_cast_fu_1217_p1));

assign tmp3_fu_1935_p2 = ($signed(tmp_157_0_1_cast_66_fu_1923_p1) + $signed(tmp4_cast_fu_1932_p1));

assign tmp4_cast_fu_1932_p1 = $signed(tmp4_reg_2608);

assign tmp4_fu_1257_p2 = ($signed(tmp_157_0_2_2_cast_c_fu_1247_p1) + $signed(sum_V_0_0_2_cast_cas_fu_1195_p1));

assign tmp5_fu_1263_p2 = (tmp_55_fu_1225_p1 + tmp_53_fu_1221_p1);

assign tmp6_fu_1954_p2 = (tmp_62_fu_1927_p2 + tmp7_reg_2618);

assign tmp7_fu_1269_p2 = (src_kernel_win_0_va_6_fu_1129_p3 + tmp_63_fu_1243_p1);

assign tmp_10_fu_631_p3 = tmp_3_fu_619_p2[32'd9];

assign tmp_115_0_1_fu_603_p2 = ((t_V_reg_519 == 9'd0) ? 1'b1 : 1'b0);

assign tmp_11_fu_657_p3 = tmp_3_fu_619_p2[32'd9];

assign tmp_12_fu_679_p1 = p_p2_i498_i_fu_671_p3[1:0];

assign tmp_139_cast_fu_625_p2 = ($signed(2'd3) + $signed(tmp_8_fu_615_p1));

assign tmp_13_fu_683_p2 = (($signed(p_p2_i498_i_fu_671_p3) < $signed(10'd480)) ? 1'b1 : 1'b0);

assign tmp_14_fu_701_p3 = p_assign_6_0_1_fu_695_p2[32'd9];

assign tmp_157_0_0_2_cast_fu_1185_p1 = src_kernel_win_0_va_8_fu_1165_p3;

assign tmp_157_0_1_cast_66_fu_1923_p1 = r_V_10_0_1_2_fu_1916_p3;

assign tmp_157_0_1_cast_fu_1217_p1 = r_V_10_0_1_fu_1211_p2;

assign tmp_157_0_2_2_cast_c_fu_1247_p1 = src_kernel_win_0_va_6_fu_1129_p3;

assign tmp_157_0_2_cast_fu_1239_p1 = r_V_10_0_2_fu_1233_p2;

assign tmp_157_1_0_2_cast_fu_1456_p1 = src_kernel_win_1_va_8_fu_1436_p3;

assign tmp_157_1_1_cast_67_fu_2022_p1 = r_V_10_1_1_2_fu_2015_p3;

assign tmp_157_1_1_cast_fu_1488_p1 = r_V_10_1_1_fu_1482_p2;

assign tmp_157_1_2_2_cast_c_fu_1518_p1 = src_kernel_win_1_va_6_fu_1400_p3;

assign tmp_157_1_2_cast_fu_1510_p1 = r_V_10_1_2_fu_1504_p2;

assign tmp_157_2_0_2_cast_fu_1709_p1 = src_kernel_win_2_va_11_fu_1689_p3;

assign tmp_157_2_1_cast_68_fu_2121_p1 = r_V_10_2_1_2_fu_2114_p3;

assign tmp_157_2_1_cast_fu_1741_p1 = r_V_10_2_1_fu_1735_p2;

assign tmp_157_2_2_2_cast_c_fu_1771_p1 = src_kernel_win_2_va_9_fu_1653_p3;

assign tmp_157_2_2_cast_fu_1763_p1 = r_V_10_2_2_fu_1757_p2;

assign tmp_15_fu_709_p3 = p_assign_6_0_1_fu_695_p2[32'd9];

assign tmp_16_fu_769_p2 = (tmp_8_fu_615_p1 ^ 2'd2);

assign tmp_17_fu_717_p1 = t_V_reg_519[1:0];

assign tmp_19_fu_727_p3 = p_assign_6_0_2_fu_721_p2[32'd9];

assign tmp_1_fu_569_p2 = ((t_V_reg_519 < 9'd480) ? 1'b1 : 1'b0);

assign tmp_1_i_i1_fu_2099_p2 = (p_Result_1_fu_2045_p3 | overflow_1_fu_2085_p2);

assign tmp_1_i_i2_fu_2198_p2 = (p_Result_2_fu_2144_p3 | overflow_2_fu_2184_p2);

assign tmp_1_i_i_fu_2000_p2 = (p_Result_s_fu_1946_p3 | overflow_fu_1986_p2);

assign tmp_20_fu_735_p3 = p_assign_6_0_2_fu_721_p2[32'd9];

assign tmp_21_fu_897_p2 = (($signed(ImagLoc_x_fu_877_p2) < $signed(11'd640)) ? 1'b1 : 1'b0);

assign tmp_22_fu_743_p1 = t_V_reg_519[1:0];

assign tmp_23_fu_931_p2 = (($signed(p_p2_i_i_fu_923_p3) < $signed(11'd640)) ? 1'b1 : 1'b0);

assign tmp_24_fu_775_p2 = ($signed(2'd2) - $signed(tmp_17_fu_717_p1));

assign tmp_25_fu_972_p1 = $unsigned(x_cast_fu_959_p1);

assign tmp_2_fu_609_p2 = ((t_V_reg_519 > 9'd480) ? 1'b1 : 1'b0);

assign tmp_30_fu_781_p1 = p_assign_6_0_1_fu_695_p2[1:0];

assign tmp_31_fu_785_p3 = ((tmp_15_fu_709_p3[0:0] === 1'b1) ? tmp_24_fu_775_p2 : tmp_30_fu_781_p1);

assign tmp_32_fu_793_p3 = ((tmp_14_fu_701_p3[0:0] === 1'b1) ? tmp_31_fu_785_p3 : tmp_16_fu_769_p2);

assign tmp_34_fu_807_p2 = (2'd1 + tmp_8_fu_615_p1);

assign tmp_35_fu_813_p2 = (tmp_22_fu_743_p1 ^ 2'd3);

assign tmp_36_fu_831_p3 = ((tmp_19_fu_727_p3[0:0] === 1'b1) ? tmp_39_fu_823_p3 : tmp_34_fu_807_p2);

assign tmp_38_fu_819_p1 = p_assign_6_0_2_fu_721_p2[1:0];

assign tmp_39_fu_823_p3 = ((tmp_20_fu_735_p3[0:0] === 1'b1) ? tmp_35_fu_813_p2 : tmp_38_fu_819_p1);

assign tmp_3_fu_619_p2 = ($signed(10'd1023) + $signed(t_V_cast_fu_553_p1));

assign tmp_40_fu_861_p4 = {{t_V_2_reg_530[9:1]}};

assign tmp_41_fu_883_p3 = ImagLoc_x_fu_877_p2[32'd10];

assign tmp_42_fu_1964_p4 = {{p_Val2_s_fu_1941_p2[10:8]}};

assign tmp_43_fu_909_p3 = ImagLoc_x_fu_877_p2[32'd10];

assign tmp_4_fu_645_p2 = (($signed(tmp_3_fu_619_p2) < $signed(10'd480)) ? 1'b1 : 1'b0);

assign tmp_50_fu_963_p1 = x_fu_951_p3[1:0];

assign tmp_53_fu_1221_p1 = sum_V_0_0_2_fu_1189_p2[7:0];

assign tmp_54_fu_2063_p4 = {{p_Val2_3_fu_2040_p2[10:8]}};

assign tmp_55_fu_1225_p1 = r_V_10_0_1_fu_1211_p2[7:0];

assign tmp_62_fu_1927_p2 = src_kernel_win_0_va_7_reg_2597 << 8'd1;

assign tmp_63_fu_1243_p1 = r_V_10_0_2_fu_1233_p2[7:0];

assign tmp_64_fu_2162_p4 = {{p_Val2_6_fu_2139_p2[10:8]}};

assign tmp_69_fu_1492_p1 = sum_V_1_0_2_fu_1460_p2[7:0];

assign tmp_6_fu_541_p2 = (tmp_5_reg_508 + 2'd1);

assign tmp_70_fu_1496_p1 = r_V_10_1_1_fu_1482_p2[7:0];

assign tmp_71_0_0_not_fu_575_p2 = (tmp_1_fu_569_p2 ^ 1'd1);

assign tmp_71_fu_2026_p2 = src_kernel_win_1_va_7_reg_2623 << 8'd1;

assign tmp_72_fu_1514_p1 = r_V_10_1_2_fu_1504_p2[7:0];

assign tmp_77_fu_1745_p1 = sum_V_2_0_2_fu_1713_p2[7:0];

assign tmp_78_fu_1749_p1 = r_V_10_2_1_fu_1735_p2[7:0];

assign tmp_79_fu_2125_p2 = src_kernel_win_2_va_10_reg_2649 << 8'd1;

assign tmp_7_fu_547_p2 = ((tmp_5_reg_508 == 2'd2) ? 1'b1 : 1'b0);

assign tmp_80_fu_1767_p1 = r_V_10_2_2_fu_1757_p2[7:0];

assign tmp_8_fu_615_p1 = t_V_reg_519[1:0];

assign tmp_9_fu_597_p2 = ((t_V_reg_519 == 9'd1) ? 1'b1 : 1'b0);

assign tmp_fu_581_p4 = {{t_V_reg_519[8:1]}};

assign tmp_i_i1_fu_2073_p2 = (p_Result_1_fu_2045_p3 ^ 1'd1);

assign tmp_i_i2_fu_2172_p2 = (p_Result_2_fu_2144_p3 ^ 1'd1);

assign tmp_i_i_fu_1974_p2 = (p_Result_s_fu_1946_p3 ^ 1'd1);

assign x_cast_fu_959_p1 = x_fu_951_p3;

assign x_fu_951_p3 = ((or_cond_i_i_fu_903_p2[0:0] === 1'b1) ? ImagLoc_x_fu_877_p2 : p_p2_i_i_p_assign_2_fu_943_p3);

assign y_fu_755_p3 = ((or_cond_i497_i_fu_651_p2[0:0] === 1'b1) ? tmp_139_cast_fu_625_p2 : p_p2_i498_i_0_p_assig_fu_747_p3);

endmodule //Filter2D
